#!/usr/bin/env python3
"""
Generate the MkDocs site scaffolding from the document catalogue.

Writes:
  - mkdocs.yml     MkDocs Material config with a tier-grouped nav built from
                   MASTER_INDEX (so the nav never drifts from the catalogue).
  - docs/index.md  Landing page: overview, coverage stats, per-tier document
                   list, and the embedded knowledge graph.

The Pages workflow runs this before `mkdocs build`, so the deployed site is
always current. Regenerate locally with `python scripts/build_site.py`.
"""
from __future__ import annotations

import re
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

INDEX = Path("MASTER_INDEX.md")
MMD = Path("exports/knowledge-graph.mmd")

TIER_NAMES = {
    "1": "Class 1 — Track foundations (Modders / Players / Admins / Creator)",
    "2": "Class 2 — Core reference (mechanics, entities, API, settings)",
    "3": "Class 3 — Guides, tutorials & runbooks",
    "4": "Class 4 — Meta, lore & creator strategy",
}

SITE_NAME = "Project Zomboid Knowledge Base (B41 & B42)"
SITE_DESC = ("Evidence-based, source-cited Project Zomboid reference for modders, "
             "players, server admins and creators — every document version-tagged "
             "for Build 41 (legacy41) and Build 42.")


def parse_docs(text: str) -> list[dict]:
    docs, in_docs = [], False
    for line in text.splitlines():
        if line.startswith("## Documents"):
            in_docs = True
            continue
        if in_docs and line.startswith("## "):
            break
        if in_docs and line.startswith("|"):
            c = [x.strip() for x in line.strip().strip("|").split("|")]
            if len(c) < 9 or c[0] in ("ID", "") or set(c[0]) <= {"-"}:
                continue
            docs.append({"id": c[0], "title": c[1], "topic": c[2], "tier": c[3],
                         "build": c[4], "version": c[5], "status": c[6],
                         "confidence": c[7], "path": c[8].strip("`")})
    return docs


def rel(path: str) -> str:
    return path[len("docs/"):] if path.startswith("docs/") else path


def build_nav(docs: list[dict]) -> str:
    by_tier: dict[str, list[dict]] = defaultdict(list)
    for d in docs:
        by_tier[d["tier"]].append(d)
    lines = ["  - Home: index.md"]
    for tier in sorted(by_tier):
        lines.append(f'  - "{TIER_NAMES.get(tier, "Tier " + tier)}":')
        for d in sorted(by_tier[tier], key=lambda x: x["path"]):
            title = d["title"].replace('"', "'")
            lines.append(f'      - "{title}": {rel(d["path"])}')
    return "\n".join(lines)


def write_mkdocs(docs: list[dict]) -> None:
    nav = build_nav(docs)
    cfg = f"""# Generated by scripts/build_site.py — do not edit by hand.
site_name: {SITE_NAME}
site_description: {SITE_DESC}
docs_dir: docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - search
nav:
{nav}
"""
    Path("mkdocs.yml").write_text(cfg, encoding="utf-8")


def write_index(docs: list[dict]) -> None:
    builds = Counter(d["build"] for d in docs)
    conf = Counter(d["confidence"] for d in docs)
    topics = {d["topic"] for d in docs}
    by_tier: dict[str, list[dict]] = defaultdict(list)
    for d in docs:
        by_tier[d["tier"]].append(d)

    L = [
        "# Project Zomboid Knowledge Base (B41 & B42)", "",
        "!!! warning \"Unofficial fan reference — not affiliated with The Indie Stone\"",
        "    This is an unofficial, community-produced research reference. It is "
        "not affiliated with, endorsed by, or sponsored by The Indie Stone. "
        "Project Zomboid and all related content are trademarks and copyrights "
        "of The Indie Stone. Every document carries a build tag (B41 / B42 / "
        "both); the game moves fast — verify against the current patch notes "
        "and in-game behaviour before relying on any value.", "",
        SITE_DESC, "",
        f"**{len(docs)} documents** across **{len(topics)} topics** — "
        f"every factual claim carries a citation to a primary or authoritative "
        f"source, unverified community claims are labelled and quarantined, and "
        f"build tags, links, citations and structure are checked automatically "
        f"in CI.", "",
        f"*Confidence: {conf.get('High',0)} High · {conf.get('Medium',0)} Medium · "
        f"{conf.get('Low',0)} Low.*  "
        f"*Build: "
        + " · ".join(f"{k} {v}" for k, v in sorted(builds.items())) + ".*", "",
    ]
    for tier in sorted(by_tier):
        L.append(f"## {TIER_NAMES.get(tier, 'Tier ' + tier)}")
        L.append("")
        for d in sorted(by_tier[tier], key=lambda x: x["path"]):
            L.append(f"- [{d['title']}]({rel(d['path'])}) "
                     f"— *{d['topic']}* ({d['build']})")
        L.append("")
    if MMD.exists():
        L += ["## Knowledge graph", "",
              '??? note "Cross-reference graph (click to expand)"', "",
              "    ```mermaid"]
        for ln in MMD.read_text(encoding="utf-8").splitlines():
            L.append("    " + ln)
        L += ["    ```", ""]
    L += ["## Machine-readable exports", "",
          "Generated artefacts live in the repository's `exports/` directory: "
          "a knowledge graph (JSON + Mermaid), a document matrix (CSV/JSON), "
          "a coverage report, and a section-level RAG export (`exports/rag/`).", "",
          "*Site generated by `scripts/build_site.py` — do not edit by hand.*",
          ""]
    Path("docs/index.md").write_text("\n".join(L) + "\n", encoding="utf-8")


def main() -> int:
    docs = parse_docs(INDEX.read_text(encoding="utf-8"))
    write_mkdocs(docs)
    write_index(docs)
    print(f"Wrote mkdocs.yml and docs/index.md ({len(docs)} documents in nav).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
